const router = require('express').Router()
const auth = require('./auth')
const users = require('./users')
const wigs = require('./wigs')
const bhag = require('./bhag')
const scorecards = require('./scorecards')
const todos = require('./todos')
const issues = require('./issues')
const meetings = require('./meetings')
const vision = require('./vision')
const reviews = require('./reviews')
const notifications = require('./notifications')

router.use('/auth', auth)
router.use('/users', users)
router.use('/wigs', wigs)
router.use('/bhag', bhag)
router.use('/scorecards', scorecards)
router.use('/todos', todos)
router.use('/issues', issues)
router.use('/meetings', meetings)
router.use('/vision', vision)
router.use('/reviews', reviews)
router.use('/notifications', notifications)

module.exports = router
